spring:
  datasource:
    url: jdbc:mysql://localhost:3306/KindredDatabase
    username: root
    password: Poudel@01

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: 8082